apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "28.2.0" # Make sure this is the version you want to use
  values:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          enabled: true
    nodePorts:
      web: 30080
      websecure: 30443
